### ISSUE TITLE
dx build_asset error

### ISSUE THREAD

**Issue by adily777** [dnanexus/dx_app_builder#20]
Hello,

I created dxasset.json file:
```
{
  "name": "python_asset",
  "title": "Example Asset",
  "description": "Libraries required for cnv_blocks app",
  "version": "0.0.1",
  "distribution": "Ubuntu",
  "instanceType": "mem2_ssd1_x4",
  "release": "16.04",
  "execDepends": [
    {"name": "statistics", "package_manager": "pip"},
    {"name": "pandas","package_manager": "pip"}
  ]
}
```
When I build it with: `dx build_asset python_asset/`
I got an error:
```
2020-02-04 13:29:15 python_asset STDOUT Collecting statistics
2020-02-04 13:29:15 python_asset STDERR   File "/home/dnanexus/job-Fjvb9vj0qG0Fy79XGYFj65ZQ.code.py", line 14, in <module>
2020-02-04 13:29:15 python_asset STDOUT   Downloading https://files.pythonhosted.org/packages/bb/3a/ae99a15e65636559d936dd2159d75af1619491e8cb770859fbc8aa62cef6/statistics-1.0.3.5.tar.gz
2020-02-04 13:29:15 python_asset STDERR     dxpy.run()
2020-02-04 13:29:15 python_asset STDOUT Collecting pandas
2020-02-04 13:29:15 python_asset STDERR   File "/usr/share/dnanexus/lib/python2.7/site-packages/dxpy/utils/exec_utils.py", line 150, in run
2020-02-04 13:29:15 python_asset STDOUT   Downloading https://files.pythonhosted.org/packages/26/c4/b3cd1c8928a496e27a8604160a4b6c672bda76cc215130848f68f01e0213/pandas-1.0.0.tar.gz (4.8MB)
2020-02-04 13:29:15 python_asset STDOUT     Complete output from command python setup.py egg_info:
2020-02-04 13:29:15 python_asset STDOUT     Traceback (most recent call last):
2020-02-04 13:29:15 python_asset STDOUT       File "<string>", line 1, in <module>
2020-02-04 13:29:15 python_asset STDOUT       File "/tmp/pip-build-XtkORV/pandas/setup.py", line 42
2020-02-04 13:29:15 python_asset STDOUT         f"numpy >= {min_numpy_ver}",
2020-02-04 13:29:15 python_asset STDERR     result = ENTRY_POINT_TABLE[job['function']](**job['input'])
2020-02-04 13:29:15 python_asset STDOUT                                   ^
2020-02-04 13:29:15 python_asset STDERR   File "/home/dnanexus/job-Fjvb9vj0qG0Fy79XGYFj65ZQ.code.py", line 12, in main
2020-02-04 13:29:15 python_asset STDOUT     SyntaxError: invalid syntax
2020-02-04 13:29:15 python_asset STDERR     return asset_builder.build_asset(conf_json, asset_makefile, custom_asset)
2020-02-04 13:29:15 python_asset STDOUT     
2020-02-04 13:29:15 python_asset STDERR   File "/opt/pythonlibs/asset_builder.py", line 136, in build_asset
2020-02-04 13:29:15 python_asset STDOUT     ----------------------------------------
2020-02-04 13:29:15 python_asset STDERR     install_run_spec(conf_data['execDepends'])
2020-02-04 13:29:15 python_asset STDOUT Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-XtkORV/pandas/
2020-02-04 13:29:15 python_asset STDERR   File "/opt/pythonlibs/asset_builder.py", line 35, in install_run_spec
2020-02-04 13:29:15 python_asset STDOUT You are using pip version 8.1.1, however version 20.0.2 is available.
2020-02-04 13:29:15 python_asset STDERR     dx_installer.install()
2020-02-04 13:29:15 python_asset STDOUT You should consider upgrading via the 'pip install --upgrade pip' command.
```
How can fix that?

Thank you,
Adily

**Comment by kpjensen** [comment]
Hi Adily,

I believe the reason for the failure to build the asset is that the pip package versions are not specified and pip attempts install the latest versions of pandas and numpy. The most recent versions of these packages no longer support Python 2. 

You can pin the versions in execDepends to the latest versions which support Python 2 as shown below.
```
"execDepends":[
    	{"name":"statistics","package_manager":"pip"},
    	{"name":"numpy","package_manager":"pip", "version":"1.16.4"},
    	{"name":"pandas","package_manager":"pip", "version":"0.24.2"}]
``` 

Kurt

**Comment by adily777** [comment]
Thank you for your answer.
I tried your suggestion but got the next error:
```
  Downloading/unpacking numpy==1.16.4
  Running setup.py (path:/tmp/pip_build_root/numpy/setup.py) egg_info for package numpy
    Running from numpy source directory.
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    
    no previously-included directories found matching 'doc/build'
    no previously-included directories found matching 'doc/source/generated'
    no previously-included directories found matching 'benchmarks/env'
    no previously-included directories found matching 'benchmarks/results'
    no previously-included directories found matching 'benchmarks/html'
    no previously-included directories found matching 'benchmarks/numpy'
    no previously-included directories found matching '*/__pycache__'
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.swp' found anywhere in distribution
    warning: no previously-included files matching '*.bak' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
Downloading/unpacking pandas==0.24.2
  Running setup.py (path:/tmp/pip_build_root/pandas/setup.py) egg_info for package pandas
    Traceback (most recent call last): File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 619, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
    ...
    File "/tmp/easy_install-tdHvUI/numpy-1.18.1/setup.py", line 32, in <module>
    RuntimeError: Python version >= 3.5 required.
----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pandas
Storing debug log for failure in /home/dnanexus/.pip/pip.log
    self._install_dep_group(dep_group)
  File "/usr/share/dnanexus/lib/python2.7/site-packages/dxpy/utils/exec_utils.py", line 429, in _install_dep_group
    raise DXExecDependencyError("Error while installing {type} packages {deps}".format(**dep_group))
dxpy.utils.exec_utils.DXExecDependencyError: Error while installing pip packages [{u'package_manager': u'pip', u'name': u'statistics'}, {u'version': u'1.16.4', u'package_manager': u'pip', u'name': u'numpy'}, {u'version': u'0.24.2', u'package_manager': u'pip', u'name': u'pandas'}]
```
